name        = "amaze"
license     = "MIT"
licenselink = "https://github.com/Heemooo/amaze/blob/master/LICENSE"
description = "All you need for a blog in one template."
homepage    = "https://github.com/Heemooo/hugo-theme-amaze"
customdemo  = "https://heemooo.gitee.io"
tags        = ["blog", "personal"]
features    = ["full image carousel", "hierachical toc", "katex"]
min_version = 0.51

[author]
  name      = "heemooo"
  homepage  = "https://heemooo.gitee.io/"
